/**
 * Database types for Supabase
 * This file will be auto-generated by Supabase CLI after running `supabase gen types typescript`
 * For now, we provide a placeholder structure
 */

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[];

export interface Database {
    public: {
        Tables: {
            organizations: {
                Row: {
                    id: string;
                    name: string;
                    type: string;
                    email: string | null;
                    phone: string | null;
                    address: Json | null;
                    metadata: Json | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    name: string;
                    type: string;
                    email?: string | null;
                    phone?: string | null;
                    address?: Json | null;
                    metadata?: Json | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    name?: string;
                    type?: string;
                    email?: string | null;
                    phone?: string | null;
                    address?: Json | null;
                    metadata?: Json | null;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            dcas: {
                Row: {
                    id: string;
                    organization_id: string | null;
                    name: string;
                    legal_name: string | null;
                    registration_number: string | null;
                    status: 'ACTIVE' | 'SUSPENDED' | 'TERMINATED' | 'PENDING_APPROVAL';
                    performance_score: number;
                    recovery_rate: number;
                    sla_compliance_rate: number;
                    avg_recovery_time_days: number | null;
                    total_cases_handled: number;
                    total_amount_recovered: number;
                    capacity_limit: number;
                    capacity_used: number;
                    max_case_value: number | null;
                    min_case_value: number | null;
                    specializations: Json | null;
                    geographic_coverage: Json | null;
                    certifications: Json | null;
                    license_expiry: string | null;
                    insurance_valid_until: string | null;
                    last_audit_date: string | null;
                    audit_score: number | null;
                    contract_start_date: string | null;
                    contract_end_date: string | null;
                    commission_rate: number | null;
                    primary_contact_name: string | null;
                    primary_contact_email: string | null;
                    primary_contact_phone: string | null;
                    metadata: Json | null;
                    created_at: string;
                    updated_at: string;
                    created_by: string | null;
                    updated_by: string | null;
                };
                Insert: {
                    id?: string;
                    organization_id?: string | null;
                    name: string;
                    legal_name?: string | null;
                    registration_number?: string | null;
                    status?: 'ACTIVE' | 'SUSPENDED' | 'TERMINATED' | 'PENDING_APPROVAL';
                    performance_score?: number;
                    recovery_rate?: number;
                    sla_compliance_rate?: number;
                    avg_recovery_time_days?: number | null;
                    total_cases_handled?: number;
                    total_amount_recovered?: number;
                    capacity_limit?: number;
                    capacity_used?: number;
                    max_case_value?: number | null;
                    min_case_value?: number | null;
                    specializations?: Json | null;
                    geographic_coverage?: Json | null;
                    certifications?: Json | null;
                    license_expiry?: string | null;
                    insurance_valid_until?: string | null;
                    last_audit_date?: string | null;
                    audit_score?: number | null;
                    contract_start_date?: string | null;
                    contract_end_date?: string | null;
                    commission_rate?: number | null;
                    primary_contact_name?: string | null;
                    primary_contact_email?: string | null;
                    primary_contact_phone?: string | null;
                    metadata?: Json | null;
                    created_at?: string;
                    updated_at?: string;
                    created_by?: string | null;
                    updated_by?: string | null;
                };
                Update: Partial<Database['public']['Tables']['dcas']['Insert']>;
            };
            users: {
                Row: {
                    id: string;
                    email: string;
                    full_name: string;
                    role: 'SUPER_ADMIN' | 'FEDEX_ADMIN' | 'FEDEX_MANAGER' | 'FEDEX_ANALYST' | 'DCA_ADMIN' | 'DCA_MANAGER' | 'DCA_AGENT' | 'AUDITOR' | 'READONLY';
                    organization_id: string | null;
                    dca_id: string | null;
                    phone: string | null;
                    avatar_url: string | null;
                    timezone: string;
                    locale: string;
                    permissions: Json | null;
                    is_active: boolean;
                    is_verified: boolean;
                    mfa_enabled: boolean;
                    last_login_at: string | null;
                    last_login_ip: string | null;
                    notification_preferences: Json | null;
                    ui_preferences: Json | null;
                    metadata: Json | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    email: string;
                    full_name: string;
                    role: 'SUPER_ADMIN' | 'FEDEX_ADMIN' | 'FEDEX_MANAGER' | 'FEDEX_ANALYST' | 'DCA_ADMIN' | 'DCA_MANAGER' | 'DCA_AGENT' | 'AUDITOR' | 'READONLY';
                    organization_id?: string | null;
                    dca_id?: string | null;
                    phone?: string | null;
                    avatar_url?: string | null;
                    timezone?: string;
                    locale?: string;
                    permissions?: Json | null;
                    is_active?: boolean;
                    is_verified?: boolean;
                    mfa_enabled?: boolean;
                    last_login_at?: string | null;
                    last_login_ip?: string | null;
                    notification_preferences?: Json | null;
                    ui_preferences?: Json | null;
                    metadata?: Json | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: Partial<Database['public']['Tables']['users']['Insert']>;
            };
            cases: {
                Row: {
                    id: string;
                    case_number: string;
                    invoice_number: string;
                    invoice_date: string;
                    due_date: string;
                    original_amount: number;
                    outstanding_amount: number;
                    currency: string;
                    customer_id: string;
                    customer_name: string;
                    customer_type: string | null;
                    customer_segment: string | null;
                    customer_industry: string | null;
                    customer_country: string | null;
                    customer_state: string | null;
                    customer_city: string | null;
                    customer_contact: Json | null;
                    customer_credit_score: number | null;
                    customer_payment_history: Json | null;
                    status: 'PENDING_ALLOCATION' | 'ALLOCATED' | 'IN_PROGRESS' | 'CUSTOMER_CONTACTED' | 'PAYMENT_PROMISED' | 'PARTIAL_RECOVERY' | 'FULL_RECOVERY' | 'DISPUTED' | 'ESCALATED' | 'LEGAL_ACTION' | 'WRITTEN_OFF' | 'CLOSED';
                    priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
                    ageing_days: number;
                    ageing_bucket: string;
                    priority_score: number | null;
                    recovery_probability: number | null;
                    ai_confidence_score: number | null;
                    risk_score: number | null;
                    last_scored_at: string | null;
                    assigned_dca_id: string | null;
                    assigned_agent_id: string | null;
                    assigned_at: string | null;
                    assignment_method: string | null;
                    recovered_amount: number;
                    recovery_percentage: number;
                    last_payment_date: string | null;
                    payment_plan_active: boolean;
                    payment_plan_details: Json | null;
                    is_disputed: boolean;
                    dispute_reason: string | null;
                    dispute_opened_at: string | null;
                    dispute_resolved_at: string | null;
                    dispute_resolution: string | null;
                    legal_action_initiated: boolean;
                    legal_action_date: string | null;
                    legal_case_number: string | null;
                    judgement_amount: number | null;
                    judgement_date: string | null;
                    closed_at: string | null;
                    closure_reason: string | null;
                    write_off_amount: number | null;
                    write_off_date: string | null;
                    roe_recommendations: Json | null;
                    roe_last_updated: string | null;
                    first_contact_date: string | null;
                    last_contact_date: string | null;
                    contact_attempts: number;
                    successful_contacts: number;
                    high_priority_flag: boolean;
                    vip_customer: boolean;
                    fraud_suspected: boolean;
                    bankruptcy_flag: boolean;
                    document_urls: Json | null;
                    tags: string[] | null;
                    internal_notes: string | null;
                    metadata: Json | null;
                    created_at: string;
                    updated_at: string;
                    created_by: string | null;
                    updated_by: string | null;
                };
                Insert: Omit<Database['public']['Tables']['cases']['Row'], 'id' | 'case_number' | 'ageing_days' | 'ageing_bucket' | 'recovery_percentage' | 'created_at' | 'updated_at'> & {
                    id?: string;
                    case_number?: string;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: Partial<Database['public']['Tables']['cases']['Insert']>;
            };
            sla_templates: {
                Row: {
                    id: string;
                    name: string;
                    sla_type: 'FIRST_CONTACT' | 'WEEKLY_UPDATE' | 'MONTHLY_REPORT' | 'RESPONSE_TO_DISPUTE' | 'RECOVERY_TARGET' | 'DOCUMENTATION_SUBMISSION';
                    description: string | null;
                    duration_hours: number;
                    business_hours_only: boolean;
                    applicable_to: Json | null;
                    breach_notification_to: string[] | null;
                    auto_escalate_on_breach: boolean;
                    escalation_rules: Json | null;
                    is_active: boolean;
                    created_at: string;
                    updated_at: string;
                };
                Insert: Omit<Database['public']['Tables']['sla_templates']['Row'], 'id' | 'created_at' | 'updated_at'> & {
                    id?: string;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: Partial<Database['public']['Tables']['sla_templates']['Insert']>;
            };
            sla_logs: {
                Row: {
                    id: string;
                    case_id: string;
                    sla_template_id: string | null;
                    sla_type: 'FIRST_CONTACT' | 'WEEKLY_UPDATE' | 'MONTHLY_REPORT' | 'RESPONSE_TO_DISPUTE' | 'RECOVERY_TARGET' | 'DOCUMENTATION_SUBMISSION';
                    started_at: string;
                    due_at: string;
                    completed_at: string | null;
                    status: 'PENDING' | 'MET' | 'BREACHED' | 'EXEMPT';
                    breach_duration_minutes: number | null;
                    is_exempt: boolean;
                    exemption_reason: string | null;
                    exempted_by: string | null;
                    exempted_at: string | null;
                    warning_sent: boolean;
                    warning_sent_at: string | null;
                    breach_notification_sent: boolean;
                    metadata: Json | null;
                    created_at: string;
                };
                Insert: Omit<Database['public']['Tables']['sla_logs']['Row'], 'id' | 'created_at'> & {
                    id?: string;
                    created_at?: string;
                };
                Update: Partial<Database['public']['Tables']['sla_logs']['Insert']>;
            };
            case_actions: {
                Row: {
                    id: string;
                    case_id: string;
                    action_type: string;
                    action_description: string | null;
                    contact_method: 'PHONE' | 'EMAIL' | 'SMS' | 'LETTER' | 'IN_PERSON' | 'LEGAL_NOTICE' | null;
                    contact_outcome: 'NO_ANSWER' | 'WRONG_NUMBER' | 'VOICEMAIL' | 'SPOKE_WITH_CUSTOMER' | 'PAYMENT_COMMITTED' | 'DISPUTE_RAISED' | 'CALLBACK_REQUESTED' | 'REFUSED_TO_PAY' | 'BANKRUPTCY_DECLARED' | null;
                    contact_duration_seconds: number | null;
                    contact_notes: string | null;
                    next_contact_scheduled: string | null;
                    payment_amount: number | null;
                    payment_method: string | null;
                    payment_reference: string | null;
                    old_status: string | null;
                    new_status: string | null;
                    status_change_reason: string | null;
                    performed_by: string;
                    performed_by_role: string;
                    performed_by_dca_id: string | null;
                    sentiment_score: number | null;
                    sentiment_label: string | null;
                    roe_recommendation_used: boolean;
                    roe_recommendation_id: string | null;
                    metadata: Json | null;
                    created_at: string;
                };
                Insert: Omit<Database['public']['Tables']['case_actions']['Row'], 'id' | 'created_at'> & {
                    id?: string;
                    created_at?: string;
                };
                Update: Partial<Database['public']['Tables']['case_actions']['Insert']>;
            };
            notifications: {
                Row: {
                    id: string;
                    recipient_id: string;
                    notification_type: 'SLA_WARNING' | 'SLA_BREACH' | 'CASE_ASSIGNED' | 'PAYMENT_RECEIVED' | 'ESCALATION_CREATED' | 'DISPUTE_RAISED' | 'PERFORMANCE_ALERT' | 'SYSTEM_ALERT';
                    title: string;
                    message: string;
                    action_url: string | null;
                    related_case_id: string | null;
                    related_escalation_id: string | null;
                    related_dca_id: string | null;
                    channels: string[];
                    is_read: boolean;
                    read_at: string | null;
                    is_dismissed: boolean;
                    priority: 'LOW' | 'NORMAL' | 'HIGH' | 'URGENT';
                    expires_at: string | null;
                    created_at: string;
                };
                Insert: Omit<Database['public']['Tables']['notifications']['Row'], 'id' | 'created_at'> & {
                    id?: string;
                    created_at?: string;
                };
                Update: Partial<Database['public']['Tables']['notifications']['Insert']>;
            };
            escalations: {
                Row: {
                    id: string;
                    case_id: string | null;
                    escalation_type: 'SLA_BREACH' | 'REPEATED_BREACH' | 'NO_PROGRESS' | 'CUSTOMER_COMPLAINT' | 'DCA_PERFORMANCE' | 'HIGH_VALUE' | 'FRAUD_SUSPECTED' | 'LEGAL_REQUIRED' | 'MANUAL';
                    title: string;
                    description: string;
                    severity: string | null;
                    status: 'OPEN' | 'IN_PROGRESS' | 'RESOLVED' | 'CLOSED';
                    escalated_to: string | null;
                    escalated_from: string | null;
                    escalated_at: string;
                    resolution: string | null;
                    resolved_by: string | null;
                    resolved_at: string | null;
                    resolution_time_hours: number | null;
                    case_reallocated: boolean;
                    new_dca_id: string | null;
                    dca_penalized: boolean;
                    penalty_details: Json | null;
                    metadata: Json | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: Omit<Database['public']['Tables']['escalations']['Row'], 'id' | 'created_at' | 'updated_at'> & {
                    id?: string;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: Partial<Database['public']['Tables']['escalations']['Insert']>;
            };
            audit_logs: {
                Row: {
                    id: string;
                    user_id: string | null;
                    user_email: string | null;
                    user_role: string | null;
                    user_ip: string | null;
                    user_agent: string | null;
                    action: string;
                    resource_type: string;
                    resource_id: string | null;
                    description: string | null;
                    changes: Json | null;
                    request_id: string | null;
                    session_id: string | null;
                    api_endpoint: string | null;
                    http_method: string | null;
                    success: boolean;
                    error_message: string | null;
                    compliance_relevant: boolean;
                    compliance_tags: string[] | null;
                    created_at: string;
                };
                Insert: Omit<Database['public']['Tables']['audit_logs']['Row'], 'id' | 'created_at'> & {
                    id?: string;
                    created_at?: string;
                };
                Update: never; // Audit logs are immutable
            };
        };
        Views: {
            dashboard_metrics: {
                Row: {
                    date: string;
                    status: string;
                    priority: string;
                    case_count: number;
                    total_outstanding: number;
                    total_recovered: number;
                    avg_ageing: number;
                    avg_priority_score: number;
                    avg_recovery_probability: number;
                };
            };
            dca_performance_metrics: {
                Row: {
                    dca_id: string;
                    dca_name: string;
                    total_cases: number;
                    recovered_cases: number;
                    total_recovered: number;
                    total_outstanding: number;
                    avg_resolution_days: number | null;
                    sla_breaches: number;
                    sla_met: number;
                    sla_compliance_rate: number;
                };
            };
        };
        Functions: {
            [key: string]: never;
        };
        Enums: {
            case_status: 'PENDING_ALLOCATION' | 'ALLOCATED' | 'IN_PROGRESS' | 'CUSTOMER_CONTACTED' | 'PAYMENT_PROMISED' | 'PARTIAL_RECOVERY' | 'FULL_RECOVERY' | 'DISPUTED' | 'ESCALATED' | 'LEGAL_ACTION' | 'WRITTEN_OFF' | 'CLOSED';
            case_priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
            dca_status: 'ACTIVE' | 'SUSPENDED' | 'TERMINATED' | 'PENDING_APPROVAL';
            user_role: 'SUPER_ADMIN' | 'FEDEX_ADMIN' | 'FEDEX_MANAGER' | 'FEDEX_ANALYST' | 'DCA_ADMIN' | 'DCA_MANAGER' | 'DCA_AGENT' | 'AUDITOR' | 'READONLY';
            sla_type: 'FIRST_CONTACT' | 'WEEKLY_UPDATE' | 'MONTHLY_REPORT' | 'RESPONSE_TO_DISPUTE' | 'RECOVERY_TARGET' | 'DOCUMENTATION_SUBMISSION';
            sla_status: 'PENDING' | 'MET' | 'BREACHED' | 'EXEMPT';
            contact_method: 'PHONE' | 'EMAIL' | 'SMS' | 'LETTER' | 'IN_PERSON' | 'LEGAL_NOTICE';
            contact_outcome: 'NO_ANSWER' | 'WRONG_NUMBER' | 'VOICEMAIL' | 'SPOKE_WITH_CUSTOMER' | 'PAYMENT_COMMITTED' | 'DISPUTE_RAISED' | 'CALLBACK_REQUESTED' | 'REFUSED_TO_PAY' | 'BANKRUPTCY_DECLARED';
            escalation_type: 'SLA_BREACH' | 'REPEATED_BREACH' | 'NO_PROGRESS' | 'CUSTOMER_COMPLAINT' | 'DCA_PERFORMANCE' | 'HIGH_VALUE' | 'FRAUD_SUSPECTED' | 'LEGAL_REQUIRED' | 'MANUAL';
            escalation_status: 'OPEN' | 'IN_PROGRESS' | 'RESOLVED' | 'CLOSED';
            notification_type: 'SLA_WARNING' | 'SLA_BREACH' | 'CASE_ASSIGNED' | 'PAYMENT_RECEIVED' | 'ESCALATION_CREATED' | 'DISPUTE_RAISED' | 'PERFORMANCE_ALERT' | 'SYSTEM_ALERT';
            notification_channel: 'IN_APP' | 'EMAIL' | 'SMS' | 'PUSH';
        };
    };
}
